image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      sudo apt remove --autoremove emacs emacs-common
      sudo add-apt-repository ppa:kelleyk/emacs
      sudo apt update
      sudo apt install emacs28
      sudo apt install davfs2
      sudo usermod -aG davfs2 gitpod
      mkdir ~/library
      mkdir ~/.davfs2
      sudo cp /etc/davfs2/secrets ~/.davfs2/secrets
      echo "/home/gitpod/library $Webdavl $Webdavp" >> ~/.davfs2/secrets
      sudo mv ~/.davfs2/secrets /etc/davfs2/secrets
      sudo cp /workspace/template-nix/fstab /etc/fstab
      git clone https://github.com/assimetrick/orgmode.git ~/org
      git clone https://github.com/assimetrick/emacs.git ~/.emacs.d
      cd ~
      wget http://archive.ubuntu.com/ubuntu/pool/universe/x/xpdf/xpdf_3.04-7_amd64.deb
      sudo apt-get install ./xpdf_3.04-7_amd64.deb
      wget http://security.ubuntu.com/ubuntu/pool/main/p/poppler/libpoppler73_0.62.0-2ubuntu2.14_amd64.deb
      sudo apt-get install ./libpoppler73_0.62.0-2ubuntu2.12_amd64.deb
      emacs


vscode:
  extensions:
    - bbenoist.Nix
