image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      sudo apt remove --autoremove emacs emacs-common
      sudo add-apt-repository ppa:kelleyk/emacs
      sudo apt update
      sudo apt install emacs28

      git clone https://github.com/assimetrick/orgmode.git ~/org
      git clone https://github.com/assimetrick/emacs.git ~/.emacs.d
      emacs


vscode:
  extensions:
    - bbenoist.Nix
