image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo apt remove --autoremove emacs emacs-common
      sudo add-apt-repository ppa:kelleyk/emacs
      sudo apt update
      sudo apt install emacs28

      git clone git@github.com:assimetrick/orgmode.git ~/org
      git clone git@github.com:assimetrick/emacs ~/.emacs.d
      emacs


vscode:
  extensions:
    - bbenoist.Nix
