image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      sudo apt remove --autoremove emacs emacs-common
      sudo add-apt-repository ppa:kelleyk/emacs
      sudo apt update
      sudo apt install emacs28
      sudo apt install davfs2
      sudo usermod -aG davfs2 gitpod
      mkdir ~/library
      mkdir ~/.davfs2
      sudo cp /etc/davfs2/secrets ~/.davfs2/secrets
      sudo chown gitpod:gitpod ~/.davfs2/secrets
      sudo chmod 600 ~/.davfs2/secrets
      sudo cp /etc/fstab ~/fstab
      echo "https://nextcloud.vers.pw/remote.php/webdav/    /home/gitpod/library    davfs    user,rw,_netdev 0 0" >> ~/fstab
      sudo mv ~/fstab /etc/fstab
      echo "/home/gitpod/library $Webdavl $Webdavp" >> ~/.davfs2/secrets
      git clone https://github.com/assimetrick/orgmode.git ~/org
      git clone https://github.com/assimetrick/emacs.git ~/.emacs.d
      emacs


vscode:
  extensions:
    - bbenoist.Nix
